### ISSUE TITLE
java.lang.NoSuchFieldException error from jacoco when running tests 

### ISSUE THREAD

**Issue by GustaveNimant** [ligi/ipfs-api-kotlin#11]
Hello

I am new in Kotlin and gradle. Very interested by your implementation of IPFS in Kotlin I tried to run your tests with gradle and I got the error described here : https://stackoverflow.com/questions/59945979/java-lang-nosuchfieldexception-erreor-from-jacoco.

Could you please tell me what to do to fix this error.
Thank you.
Emile Achadde (emile.achadde@free.fr)

**Comment by ligi** [comment]
sorry to hear this - unfortunately I cannot reproduce the problem:

```
commit aba2625ca9ca856c4ead064911b540c5aa3f6385 (HEAD -> master)
Author: ligi <ligi@ligi.de>
Date:   Sun Jan 13 19:40:57 2019 +0100

    Use gradle 5.1.1
✓ ~/g/ipfs-api-kotlin (master $%>) ./gradlew clean build                08:30:50
w: /home/ligi/git/ipfs-api-kotlin/src/main/kotlin/io/ipfs/kotlin/commands/Add.kt: (34, 69): Parameter 'name' is never used

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
7 actionable tasks: 7 executed
```

**Comment by GustaveNimant** [comment]
I installed gradle 5.1.1 run ./gradlew clean build and get the same error. May be something due to Java ?

**Comment by GustaveNimant** [comment]
0

The issue comes from the Java version which needs not to be too recent.

sdk install java 19.3.0.2.r8-grl

makes things ok.
