### ISSUE TITLE
Get cat Bytes Method

### ISSUE THREAD

**Issue by daniel-cook** [ligi/ipfs-api-kotlin#9]
Do you have plans to spin off a new release that includes the Get catBytes method?  I see it in the repo but not in V 0.12 and would like to play around with it without cloning the whole repo.  
Thanks!

**Comment by ligi** [comment]
sorry - forgot to tag a new version - just pushed 0.13 with this change - let me know if you need anything else

**Comment by daniel-cook** [comment]
Great, thanks!
